// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 22.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class MyAssets {
  static const String package = 'sdm_digital';

  static const String assetsIconsCalendarSvg = 'assets/icons/calendar.svg';

  static const String assetsIconsEyeSvg = 'assets/icons/eye.svg';

  static const String assetsIconsFacebookMessengerAltSvg = 'assets/icons/facebook-messenger-alt.svg';

  static const String assetsIconsHomeOffSvg = 'assets/icons/home_off.svg';

  static const String assetsIconsHomeOnSvg = 'assets/icons/home_on.svg';

  static const String assetsIconsInfoSvg = 'assets/icons/info.svg';

  static const String assetsIconsLocationSvg = 'assets/icons/location.svg';

  static const String assetsIconsNotifikasiOffSvg = 'assets/icons/notifikasi_off.svg';

  static const String assetsIconsNotifikasiOnSvg = 'assets/icons/notifikasi_on.svg';

  static const String assetsIconsProfileOffSvg = 'assets/icons/profile_off.svg';

  static const String assetsIconsProfileOnSvg = 'assets/icons/profile_on.svg';

  static const String assetsIconsRiwayatOffSvg = 'assets/icons/riwayat_off.svg';

  static const String assetsIconsRiwayatOnSvg = 'assets/icons/riwayat_on.svg';

  static const String assetsImagesClspPng = 'assets/images/clsp.png';

  static const String assetsImagesKkniPng = 'assets/images/kkni.png';

  static const String assetsImagesKominfoPng = 'assets/images/kominfo.png';

  static const String assetsImagesLihatSemuaPng = 'assets/images/lihat_semua.png';

  static const String assetsImagesLspPng = 'assets/images/lsp.png';

  static const String assetsImagesPetaOkupasiPng = 'assets/images/peta_okupasi.png';

  static const String assetsImagesSertifikasiGlobalPng = 'assets/images/sertifikasi_global.png';

  static const String assetsImagesSertifikasiNasionalPng = 'assets/images/sertifikasi_nasional.png';

  static const String assetsImagesSkkniPng = 'assets/images/skkni.png';
}
